In [3]:
import numpy as np

In [ ]:
#Creating arrays 

a=np.array([1,2,3])
print("A=",a)

b=np.array([[1,2,3],[1,2,3]])
print("B=",b)

A= [1 2 3]
B= [[1 2 3]
 [1 2 3]]
C= [list([[1, 2], [3, 4]]) list([[5, 6]]) list([[1, 2, 3]])]


In [33]:
#Creating arrays from  prefilled
c=np.ones((3,3,2),dtype=int)
print("C=",c)

d=np.zeros((3,3),dtype=int)
print("D=",d)

e=np.full((2,2),5)
print("E=",e)

C= [[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
D= [[0 0 0]
 [0 0 0]
 [0 0 0]]
E= [[5 5]
 [5 5]]


In [30]:
#Getting dimensions and sizes
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print("Shapes")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

1
2
3
2
Shapes
(3,)
(2, 3)
(3, 3, 2)
(3, 3)


In [43]:
#Radom arrays

arr=np.random.randint(5,10,size=(2,2,2))
print(arr)



[[[7 8]
  [9 6]]

 [[7 9]
  [5 9]]]


In [45]:
#Matrix Operations
#Matrix Addition

matA=np.random.randint(1,10,size=(3,3))
matB=np.random.randint(1,10,size=(3,3))
print(matA)
print(matB)
print(matA+matB)

[[2 6 6]
 [1 4 9]
 [2 7 3]]
[[8 7 7]
 [8 5 9]
 [6 4 7]]
[[10 13 13]
 [ 9  9 18]
 [ 8 11 10]]


In [ ]:
#Matrix Multiplication and identity
matA=np.random.randint(1,10,size=(3,3))
matB=np.identity(3,dtype=int)
print(matA)
print(matB)
print(matA.dot(matB))
print(np.matmul(matA,matB))


[[7 5 1]
 [8 9 1]
 [8 5 4]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[7 5 1]
 [8 9 1]
 [8 5 4]]
[[7 5 1]
 [8 9 1]
 [8 5 4]]


In [62]:
#Transpose , determinant and inverse
print(matA.transpose())
print(matA.T)

print(np.linalg.inv(matA))

print(np.linalg.det(matA))
print(np.linalg.det(matB))

print(np.trace(matA))


[[7 8 8]
 [5 9 5]
 [1 1 4]]
[[7 8 8]
 [5 9 5]
 [1 1 4]]
[[ 0.47692308 -0.23076923 -0.06153846]
 [-0.36923077  0.30769231  0.01538462]
 [-0.49230769  0.07692308  0.35384615]]
64.99999999999999
1.0
20


In [70]:
#Aggregate and statistical functions along the axis 
print(matA)
print(matA.min(axis=0))
print(matA.sum(axis=1))


[[7 5 1]
 [8 9 1]
 [8 5 4]]
[7 5 1]
[13 18 17]


In [75]:
print(np.random.random(10))
print(np.random.rand(10))

[0.81202133 0.59774301 0.0575472  0.25823032 0.9424455  0.50280102
 0.04365593 0.19755501 0.47492531 0.60705039]
[0.6038976  0.05184417 0.40954387 0.63402072 0.27837008 0.78101925
 0.10308426 0.7462886  0.46201894 0.58195432]
